# Generated by Django 5.0.6 on 2024-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('keywords', models.TextField(blank=True, db_column='Keywords', primary_key=True, serialize=False)),
                ('count', models.BigIntegerField(blank=True, db_column='Count', null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
