# Generated by Django 5.0.6 on 2024-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('keywords', models.TextField(blank=True, db_column='Keywords', primary_key=True, serialize=False)),
                ('count', models.BigIntegerField(blank=True, db_column='Count', null=True)),
            ],
            options={
                'db_table': None,
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
